-- s1
BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;
-- s2
BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;
-- s1
SHOW TRANSACTION ISOLATION LEVEL;
-- s2
SHOW TRANSACTION ISOLATION LEVEL;
-- s1
SELECT SUM(rating) FROM pizzeria;
-- s2
UPDATE pizzeria SET rating = 5 WHERE name = 'Pizza Hut';
COMMIT;
-- s1
SELECT SUM(rating) FROM pizzeria;
COMMIT;
-- s1
SELECT SUM(rating) FROM pizzeria;
-- s2
SELECT SUM(rating) FROM pizzeria;